#!/usr/bin/python3
Square = __import__('10-square').Square

s = Square(13)

print(s)
print(s.area())
print("---")
print(dir(Square))
# print(issubclass(Square, Rectangle))
print("---")
s = Square(4)
print(s)
print(s.area())
print("---")
s = Square(1340)
print(s)
print(s.area())
print("---")
# s = Square()
# print(s)
# print(s.area())
print("---")
s = Square(-13)
print(s)
print(s.area())
# print(s.width)
# print(s.height)
print("---")
